create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key,
  email text unique not null,
  full_name text not null,
  phone text,
  role text not null check (role in ('user', 'physiotherapist')),
  age int,
  gender text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_health_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  full_name text not null,
  age int not null check (age between 5 and 120),
  gender text not null,
  height_cm double precision not null check (height_cm between 80 and 230),
  weight_kg double precision not null check (weight_kg between 20 and 250),
  occupation text,
  sitting_hours_per_day double precision not null default 0
    check (sitting_hours_per_day between 0 and 24),
  computer_hours_per_day double precision not null default 0
    check (computer_hours_per_day between 0 and 24),
  has_posture_condition_history boolean not null default false,
  posture_conditions jsonb not null default '[]'::jsonb,
  has_surgery_history boolean not null default false,
  surgery_areas jsonb not null default '[]'::jsonb,
  has_regular_pain boolean not null default false,
  pain_areas jsonb not null default '[]'::jsonb,
  pain_severity double precision not null default 0
    check (pain_severity between 0 and 10),
  weekly_exercise_frequency text not null,
  usage_goals jsonb not null default '[]'::jsonb,
  risk_level text not null check (risk_level in ('low', 'medium', 'high')),
  raw_profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.physiotherapists (
  id uuid primary key references public.profiles(id) on delete cascade,
  email text unique not null,
  full_name text not null,
  clinic_name text not null,
  specialty text not null,
  services text,
  working_hours text,
  bio text,
  online_consultation boolean not null default true,
  phone text,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.support_requests (
  id uuid primary key default gen_random_uuid(),
  physiotherapist_id uuid references public.physiotherapists(id) on delete cascade,
  physiotherapist_email text not null,
  physiotherapist_name text not null,
  user_id uuid references public.profiles(id) on delete cascade,
  user_email text not null,
  user_name text not null,
  user_phone text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'accepted', 'done')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.support_requests(id) on delete cascade,
  sender_role text not null check (sender_role in ('user', 'physiotherapist')),
  sender_name text not null,
  sender_email text not null,
  receiver_email text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_consents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  consent_key text not null,
  version text not null default 'v1',
  granted boolean not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  ble_identifier text not null,
  ble_name text,
  firmware_version text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (user_id, ble_identifier)
);

create table if not exists public.posture_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id uuid references public.devices(id) on delete set null,
  sensitivity text not null check (sensitivity in ('strict', 'balanced', 'relaxed')),
  calibration_pitch_offset double precision not null default 0,
  calibration_roll_offset double precision not null default 0,
  started_at timestamptz not null,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.posture_samples (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid references public.posture_sessions(id) on delete set null,
  device_id uuid references public.devices(id) on delete set null,
  measured_at timestamptz not null,
  score smallint not null check (score between 0 and 100),
  posture_state smallint not null check (posture_state between 0 and 3),
  pitch_deg double precision,
  roll_deg double precision,
  raw_pitch_deg double precision,
  raw_roll_deg double precision,
  sensitivity text check (sensitivity in ('strict', 'balanced', 'relaxed')),
  created_at timestamptz not null default now()
);

create table if not exists public.posture_daily_stats (
  user_id uuid not null references public.profiles(id) on delete cascade,
  day date not null,
  avg_score smallint not null check (avg_score between 0 and 100),
  tracking_minutes integer not null default 0,
  bad_posture_minutes integer not null default 0,
  break_count integer not null default 0,
  sample_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, day)
);

create table if not exists public.exercise_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  exercise_code text not null,
  duration_seconds integer,
  completed_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_chat_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null default 'Postur Asistani',
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.ai_chat_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.ai_chat_threads(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  safety_level text not null default 'general'
    check (safety_level in ('general', 'caution', 'urgent')),
  posture_context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_devices_user on public.devices (user_id);
create index if not exists idx_health_profiles_risk
  on public.user_health_profiles (risk_level);
create index if not exists idx_posture_sessions_user_start
  on public.posture_sessions (user_id, started_at desc);
create index if not exists idx_posture_samples_user_time
  on public.posture_samples (user_id, measured_at desc);
create index if not exists idx_posture_samples_session_time
  on public.posture_samples (session_id, measured_at);
create index if not exists idx_posture_daily_stats_user_day
  on public.posture_daily_stats (user_id, day);
create index if not exists idx_ai_threads_user_time
  on public.ai_chat_threads (user_id, last_message_at desc);
create index if not exists idx_ai_messages_thread_time
  on public.ai_chat_messages (thread_id, created_at asc);

alter table public.profiles enable row level security;
alter table public.user_health_profiles enable row level security;
alter table public.physiotherapists enable row level security;
alter table public.support_requests enable row level security;
alter table public.messages enable row level security;
alter table public.user_consents enable row level security;
alter table public.devices enable row level security;
alter table public.posture_sessions enable row level security;
alter table public.posture_samples enable row level security;
alter table public.posture_daily_stats enable row level security;
alter table public.exercise_logs enable row level security;
alter table public.ai_chat_threads enable row level security;
alter table public.ai_chat_messages enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "health_profiles_own_all" on public.user_health_profiles;
drop policy if exists "physiotherapists_select_all" on public.physiotherapists;
drop policy if exists "physiotherapists_insert_own" on public.physiotherapists;
drop policy if exists "physiotherapists_update_own" on public.physiotherapists;
drop policy if exists "support_requests_select_participants" on public.support_requests;
drop policy if exists "support_requests_insert_user" on public.support_requests;
drop policy if exists "support_requests_update_physio" on public.support_requests;
drop policy if exists "messages_select_participants" on public.messages;
drop policy if exists "messages_insert_participants" on public.messages;
drop policy if exists "user_consents_own_insert" on public.user_consents;
drop policy if exists "user_consents_own_select" on public.user_consents;
drop policy if exists "devices_own_all" on public.devices;
drop policy if exists "posture_sessions_own_all" on public.posture_sessions;
drop policy if exists "posture_samples_own_all" on public.posture_samples;
drop policy if exists "posture_daily_stats_own_all" on public.posture_daily_stats;
drop policy if exists "exercise_logs_own_all" on public.exercise_logs;
drop policy if exists "ai_threads_own_all" on public.ai_chat_threads;
drop policy if exists "ai_messages_own_all" on public.ai_chat_messages;

create policy "profiles_select_all"
on public.profiles for select
using (true);

create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "health_profiles_own_all"
on public.user_health_profiles for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "physiotherapists_select_all"
on public.physiotherapists for select
using (true);

create policy "physiotherapists_insert_own"
on public.physiotherapists for insert
with check (auth.uid() = id);

create policy "physiotherapists_update_own"
on public.physiotherapists for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "support_requests_select_participants"
on public.support_requests for select
using (auth.uid() = user_id or auth.uid() = physiotherapist_id);

create policy "support_requests_insert_user"
on public.support_requests for insert
with check (auth.uid() = user_id);

create policy "support_requests_update_physio"
on public.support_requests for update
using (auth.uid() = physiotherapist_id)
with check (auth.uid() = physiotherapist_id);

create policy "messages_select_participants"
on public.messages for select
using (
  exists (
    select 1
    from public.support_requests sr
    where sr.id = messages.thread_id
      and (sr.user_id = auth.uid() or sr.physiotherapist_id = auth.uid())
  )
);

create policy "messages_insert_participants"
on public.messages for insert
with check (
  exists (
    select 1
    from public.support_requests sr
    where sr.id = messages.thread_id
      and (sr.user_id = auth.uid() or sr.physiotherapist_id = auth.uid())
  )
);

create policy "user_consents_own_insert"
on public.user_consents for insert
with check (auth.uid() = user_id);

create policy "user_consents_own_select"
on public.user_consents for select
using (auth.uid() = user_id);

create policy "devices_own_all"
on public.devices for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "posture_sessions_own_all"
on public.posture_sessions for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "posture_samples_own_all"
on public.posture_samples for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "posture_daily_stats_own_all"
on public.posture_daily_stats for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "exercise_logs_own_all"
on public.exercise_logs for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "ai_threads_own_all"
on public.ai_chat_threads for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "ai_messages_own_all"
on public.ai_chat_messages for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
